services:
   fluree-n1:
     image: fluree/ledger:latest
     container_name: fluree1
     networks:
       - default
     ports:
       - "8090:8090"  # HTTP API port
     volumes:
       - ./fluree-data:/var/lib/fluree  # Persist Fluree data
     restart: unless-stopped


